### ISSUE TITLE
Error message could be nicer when `git done` is run outside a repository

### ISSUE THREAD

**Issue by anttikissa** [staltz/git-done#3]
The first thing I saw was this:

```
Successfully installed GitPython-0.3.2rc1 git-done-2.0.0 gitdb-0.6.4 smmap-0.9.0 termcolor-1.1.0
spinoza:~% git done
Traceback (most recent call last):
  File "/usr/local/bin/git-done", line 8, in <module>
    gitdone.main()
  File "/Library/Python/2.7/site-packages/gitdone/__init__.py", line 93, in main
    repo = git.Repo(os.path.abspath(os.curdir.decode(sys.stdin.encoding)))
  File "/Library/Python/2.7/site-packages/git/repo/base.py", line 122, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /Users/antti
```

**Comment by arpit1997** [comment]
Yeah that message does not seem to be pretty to a user. I can say that it is just an exception which is not handled so putting a few lines of code will do the wok.
here instead of this

```
repo = git.Repo(os.path.abspath(os.curdir.decode(sys.stdin.encoding)))
```

we can do something like this

```
try:
    repo = git.Repo(os.path.abspath(os.curdir.decode(sys.stdin.encoding)))
except git.exc.InvalidGitRepositoryError:
    print("Not a git repository")
    sys.exit(1)
```
